version: '2'
services:
  web:
    image: odoo:12
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ~/Workspace/projets/AssurPlus_/modules:/mnt/extra-addons
    restart: always
    container_name: odoo
  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ~/Workspace/projets/AssurPlus_/odoo-db-data:/var/lib/postgresql/data/pgdata
    restart: always
    container_name: bd
volumes:
  odoo-db-data:

   
